//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> summ { get; set; }
        public Nullable<int> payment_status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> assortment_id { get; set; }
    
        public virtual Assortment Assortment { get; set; }
        public virtual User User { get; set; }
    }
}
